version: 2

jobs:
  build_backend:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo/backend

    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

          name: run tests
          command: |
            . venv/bin/activate
            pytest

      - run:
          name: run test-coverage
          command: |
            pytest --cov-report html:cov_html --cov-report xml:cov.xml --cov-report annotate:cov_annotate --cov=application application/tests/

      - store_artifacts:
          path: test-reports
          destination: test-reports
  
  build_frontend:
    working_directory: ~/repo/frontend
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: 'npm run test-coverage'

  deploy_heroku:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: build frontend and install dependencies
          command: |
            PROJECT_ROOT=$(pwd)
            cd backend/application/ && rm -rf built_frontend/
            cd ../../frontend/ && rm -rf build/
            npm install && npm run build && cp -r build/ ../backend/application/ && cd ../backend/application/ && mv build/ built_frontend/ && cd $PROJECT_ROOT
            cd backend/ && python3 run.py
            git add . && git commit -m "Automatic build step"
      - run:
          name: deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build_backend
      - build_frontend
      - deploy_heroku:
          requires:
            - build_backend
            - build_frontend
          filters:
            branches:
              only: master
