version: 2

jobs:
  build_backend:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo/backend

    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "../requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ../requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "../requirements.txt" }}

          name: run tests
          command: |
            . venv/bin/activate
            pytest
      
      - store_artifacts:
          path: test-reports
          destination: test-reports
  
  build_frontend:
    working_directory: ~/repo/frontend
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: 'npm run test-coverage'

  deploy_heroku:
    docker:
      - image: circleci/node:10.16.3

    working_directory: ~/repo/

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: build frontend and install dependencies
          command: |
            echo "rm -rf ../../frontend/build/"
            rm -rf ../../frontend/build/
            echo "cd frontend"
            cd frontend
            echo "npm install"
            npm install
            echo "npm run build"
            npm run build 
            echo "cp -r build/ ../backend/application/ "
            cp -r build/ ../backend/application/ 
            echo "cd ../backend/application/"
            cd ../backend/application/ 
            echo "mv build/ built_frontend/"
            mv build/ built_frontend/ 
            echo "cd .."
            cd ..
             
      - save_cache:
          key: dependency-cache-{{ checksum "frontend/package-lock.json" }}
          paths:
            - frontend/node_modules
      - run:
          name: deploy to Heroku
          command: |
            git config --global user.email "circle@ci.com"
            git config --global user.name "CircleCi"
            git add . && git commit -m "Automatic build step"
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master --force

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build_backend
      - build_frontend
      - deploy_heroku:
          requires:
            - build_backend
            - build_frontend
          filters:
            branches:
              only: master
